name: Build

on:
  - push
  - pull_request

env:
  GERRIT_VERSION: "v3.6.1"
  BAZEL_VERSION: "5.2.0"

jobs:
  build:
    name: build
    runs-on: ubuntu-22.04

    steps:
      - name: checkout.self
        uses: actions/checkout@v3
        with:
          path: gerrit-checks-mock
      - name: checkout.gerrit
        run: |
          git clone \
            --depth 1 \
            --recurse-submodules \
            --branch ${{ env.GERRIT_VERSION }} \
            https://gerrit.googlesource.com/gerrit
      - run: |
          ln -s ../../gerrit-checks-mock gerrit/plugins/checks-mock
      - name: download.bazel
        uses: robinraju/release-downloader@v1.4
        with:
          repository: bazelbuild/bazel
          tag: "5.2.0"
          fileName: bazel-${{ env.BAZEL_VERSION }}-linux-x86_64
          tarball: false
          zipball: false
      - name: test
        run: |
          chmod a+x bazel-${BAZEL_VERSION}-linux-x86_64
          ln -s bazel-${BAZEL_VERSION}-linux-x86_64 bazel
          ./bazel --help
      - name: build
        run: |
          cd gerrit
          ../bazel build plugins/checks-mock:checks-mock
      - name: artifact.upload
        uses: actions/upload-artifact@v3
        with:
          name: checks-mock-plugin-${{ env.GERRIT_VERSION }}
          path: |
            gerrit/bazel-bin/plugins/checks-mock/checks-mock.jar
