name: Build

on:
  - push
  - pull_request

env:
  GERRIT_VERSION: "v3.11.1"
  BAZEL_VERSION: "7.2.1"
  CACHE_VERSION: 5

jobs:
  build:
    name: build
    runs-on: ubuntu-24.04

    steps:
      - name: download.bazel
        uses: robinraju/release-downloader@v1.9
        with:
          repository: bazelbuild/bazel
          tag: "${{ env.BAZEL_VERSION }}"
          fileName: bazel-${{ env.BAZEL_VERSION }}-linux-x86_64
          tarball: false
          zipball: false
      - name: fixups
        run: |
          chmod a+x bazel-${BAZEL_VERSION}-linux-x86_64
          ln -s bazel-${BAZEL_VERSION}-linux-x86_64 bazel
      - name: cache.bazel
        uses: actions/cache@v4
        with:
          path: ~/.cache/bazel
          key: bazel-cache-${{ env.CACHE_VERSION }}
      - name: checkout.self
        uses: actions/checkout@v4
        with:
          path: gerrit-checks-mock
      - name: checkout.gerrit
        run: |
          git clone \
            --depth 1 \
            --recurse-submodules \
            --branch ${{ env.GERRIT_VERSION }} \
            https://gerrit.googlesource.com/gerrit
      - name: link
        working-directory: gerrit
        run: |
          ln -s ../../gerrit-checks-mock plugins/checks-mock
      - name: build
        working-directory: gerrit
        run: |
          ../bazel build --noenable_bzlmod //plugins/checks-mock
      - name: artifact.upload
        uses: actions/upload-artifact@v4
        with:
          name: checks-mock-plugin-${{ env.GERRIT_VERSION }}
          path: |
            gerrit/bazel-bin/plugins/checks-mock/checks-mock.jar
