name: Build

on:
  - push
  - pull_request

env:
  BAZEL_VERSION: "3.10"
  GERRIT_VERSION: "py310"

jobs:
  build:
    name: build
    runs-on: ubuntu-22.04

    steps:
      - name: checkout.gerrit
        uses: actions/checkout@v3
        with:
          repository: https://gerrit.googlesource.com/gerrit
          ref: v3.6.1
          submodules: recursive
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: plugins/checks-mock
      - run: |
          ls -la plugins
          ls -la plugins/checks-mock
      - name: download.bazel
        uses: robinraju/release-downloader@v1.4
        with:
          repository: bazelbuild/bazel
          tag: "5.2.0"
          fileName: bazel-5.2.0-linux-x86_64
          tarball: false
          zipball: false
